# Uncomment the next line to define a global platform for your projec
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.0'

target 'RxSwiftHelloWorld' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift', '~> 6.6.0'
  pod 'RxCocoa', '~> 6.6.0'
  pod 'RxDataSources', '~> 5.0'
  pod "RxGesture", '~> 4.0.4'
  
  pod 'SnapKit', '~> 5.6.0'

  target 'RxSwiftHelloWorldTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxSwiftHelloWorldUITests' do
    # Pods for testing
  end

end
