# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OC_RxSwiftHelloWorld' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  use_modular_headers!
  use_frameworks! :linkage => :static

  pod 'RxSwift', '~> 6.6.0'
  pod 'RxCocoa', '~> 6.6.0'
  pod 'RxDataSources', '~> 5.0'
  pod 'SnapKit', '~> 5.6.0'

  target 'OC_RxSwiftHelloWorldTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OC_RxSwiftHelloWorldUITests' do
    # Pods for testing
  end

end
